Revert "fix(morphe): add headless mode and missing desktop dependencies (jna, compose-material3) to fix NoClassDefFoundError"
This reverts commit 9719b5f1f0d3761e10fa659733549af54e090ea0.